### ISSUE TITLE
Docker level=error msg="Error listening to socket: listen ip4:icmp 0.0.0.0: socket: operation not permitted"

### ISSUE THREAD

**Issue by veer123prathap** [StianOvrevage/stian.tech#1]
Hi Stian,
I  need your help regarding black box exporter we are facing the same issues
our black box exporter was running on openshift container 

Question:
how did you resolve that issue will you please guide me
where should I need to make changes at container level or target server-side
will you please help me with this, please
Ref: https://github.com/prometheus/blackbox_exporter/issues/14

Thank you

**Comment by StianOvrevage** [comment]
Hi!

It should have been fixed with the update they did to the container 4 years ago. Are you using the latest image version? Try using a tagged Docker image, for example:

```
docker pull prom/blackbox-exporter:v0.18.0
```

**Comment by veer123prathap** [comment]
we are using v0.16.0
Do we need root access for container where black box exporter running

**Comment by StianOvrevage** [comment]
Try v0.18.0 then.

If that does not work then you may need to use root / privileged access, yes.

**Comment by veer123prathap** [comment]
FROM        quay.io/prometheus/busybox:latest
COPY blackbox.yml       /etc/blackbox_exporter/config.yml
USER root
EXPOSE      9115
ENTRYPOINT  [ "/bin/blackbox_exporter" ]
CMD         [ "-config.file=/etc/blackbox_exporter/config.yml" ]

**Comment by veer123prathap** [comment]
this is our docker file still we are facing same issue

**Comment by StianOvrevage** [comment]
I don't have experience with Openshift and how it deals with permissions. You may have more luck creating an issue or asking in an Openshift community, or directly in the prometheus repos.

**Comment by veer123prathap** [comment]
We need to apply this config at target serve side 
 distribution may configure net.ipv4.ping_group_range by default in /etc/sysctl.conf or similar. If not you can set net.ipv4.ping_group_range = 0 2147483647 to allow any user the ability to use ping.
do we need to run this config at container side where black running
Alternatively the capability can be set by executing setcap cap_net_raw+ep blackbox_exporter
is that right
is something wrong please correct me
